import MswProvider from "@/components/providers/mswProvider";
import { initNodeMSW } from "@/mocks";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

initNodeMSW();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MswProvider>{children}</MswProvider>
      </body>
    </html>
  );
}
